### PR TITLE
NOT FOR MERGE. Need help with deciding what form of graph better

### PR DESCRIPTION
**Pull request by MaxSukhovetskyi**

### CODE REVIEW

**Review by viktormovchaniuk — COMMENTED** [review]
graph_v2 look good for me

**Comment by VitaliiBondar** [comment]
graph_new_v1 or graph_new_v2

**Comment by EvanAntoni** [comment]
graph_new_v2 :heavy_check_mark:

**Comment by MaxSukhovetskyi** [comment]
graph_new_v2 is a WINNER!!!!

**Pull request closed without merging**
